CC = gcc
CFLAGS = -g -Wall
OBJDIR = ../sbin

all: $(OBJDIR)/passgen $(OBJDIR)/remind $(OBJDIR)/jokey

$(OBJDIR)/passgen: 
	$(MAKE) -C passgen/

$(OBJDIR)/remind: 
	$(MAKE) -C remind/

$(OBJDIR)/jokey:
	$(MAKE) -C jokey/


